config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root 'main#index'

  resources :fighters, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'fighters#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fighter.rb
class Fighter < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_fighter

  def current_fighter
    @current_fighter ||= Fighter.find_by(id: session[:fighter_id])
  end
end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  before_action :set_fighter, only: [:show, :edit, :update, :destroy]

  # GET /fighters/new
  def new
    @fighter = Fighter.new
  end

  # POST /fighters
  # POST /fighters.json
  def create
    @fighter = Fighter.new(fighter_params)

    respond_to do |format|
      if @fighter.save
        format.html { redirect_to root_path, notice: 'Fighter was successfully created.' }
        format.json { render :show, status: :created, location: @fighter }
      else
        format.html { render :new }
        format.json { render json: @fighter.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fighter
      @fighter = Fighter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fighter_params
      params.require(:fighter).permit(:name, :password, :password_confirmation)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    fighter = Fighter.find_by_name(params[:name])
    if fighter and fighter.authenticate(params[:password])
      session[:fighter_id] = fighter.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    session[:fighter_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fighters_helper.rb
module FightersHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/fighters/_form.html.erb
<%= form_with(model: fighter, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fighters/edit.html.erb
<h1>Editing Fighter</h1>

<%= render 'form', fighter: @fighter %>

<%= link_to 'Show', @fighter %> |
<%= link_to 'Back', fighters_path %>

app/views/fighters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fighters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fighters.each do |fighter| %>
      <tr>
        <td><%= fighter.name %></td>
        <td><%= link_to 'Show', fighter %></td>
        <td><%= link_to 'Edit', edit_fighter_path(fighter) %></td>
        <td><%= link_to 'Destroy', fighter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fighter', new_fighter_path %>

app/views/fighters/new.html.erb
<h1>New Fighter</h1>

<%= render 'form', fighter: @fighter %>

app/views/fighters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fighter.name %>
</p>

<%= link_to 'Edit', edit_fighter_path(@fighter) %> |
<%= link_to 'Back', fighters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fighters</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='header'>
      <h1>FIGHTERS</h1>
      <h3>Game For True Men</h3>
    </div>
    <div class='content'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<h3>Welcome to the game!</h3>

<% if current_fighter %>
  <p>
    You logged in as <strong><%= current_fighter.name %></strong>
    <%= link_to 'Log Out', logout_path %>
  </p>
<% else %>
  <p><%= button_to 'Sign up as new Fighter', signup_path, method: :get %></p>
  <p><%= button_to 'Log in as existing Fighter', login_path, method: :get %></p>
<% end %>